import { ChangeEvent, FormEvent, useState } from 'react'
import dayjs from 'dayjs'
import { useDataContext } from '../context/DataContext'
import { useAuth } from '../context/AuthContext'
import { EstateProfile } from '../types'
import { formatDateInput } from '../utils/date'
import { downloadFile } from '../utils/export'

interface ProfileFormState {
  decedentFullName: string
  dateOfDeath: string
  county: string
  state: string
  fileNumber: string
  lettersGrantedDate: string
  firstAdvertisementDate: string
  contactName: string
  contactEmail: string
  contactPhone: string
  contactAddress: string
}

const toFormState = (profile: EstateProfile | null): ProfileFormState => ({
  decedentFullName: profile?.decedentFullName ?? '',
  dateOfDeath: formatDateInput(profile?.dateOfDeath) ?? '',
  county: profile?.county ?? 'Chester',
  state: profile?.state ?? 'PA',
  fileNumber: profile?.fileNumber ?? '',
  lettersGrantedDate: formatDateInput(profile?.lettersGrantedDate) ?? '',
  firstAdvertisementDate: formatDateInput(profile?.firstAdvertisementDate) ?? '',
  contactName: profile?.contactName ?? '',
  contactEmail: profile?.contactEmail ?? '',
  contactPhone: profile?.contactPhone ?? '',
  contactAddress: profile?.contactAddress ?? ''
})

export const SettingsPage = () => {
  const { profile, saveProfile, settings, updateSettings, exportBackup, importBackup, clearAll } = useDataContext()
  const { rememberDevice, setRememberDevice } = useAuth()
  const [form, setForm] = useState<ProfileFormState>(() => toFormState(profile))
  const [importError, setImportError] = useState('')
  const [clearing, setClearing] = useState(false)

  const handleChange = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = event.target
    setForm((prev) => ({ ...prev, [name]: value }))
  }

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault()
    const payload: EstateProfile = {
      decedentFullName: form.decedentFullName.trim(),
      dateOfDeath: form.dateOfDeath ? dayjs(form.dateOfDeath).toISOString() : '',
      county: form.county.trim(),
      state: form.state.trim(),
      fileNumber: form.fileNumber.trim() || undefined,
      lettersGrantedDate: form.lettersGrantedDate ? dayjs(form.lettersGrantedDate).toISOString() : '',
      firstAdvertisementDate: form.firstAdvertisementDate ? dayjs(form.firstAdvertisementDate).toISOString() : undefined,
      contactName: form.contactName.trim() || undefined,
      contactEmail: form.contactEmail.trim() || undefined,
      contactPhone: form.contactPhone.trim() || undefined,
      contactAddress: form.contactAddress.trim() || undefined
    }
    await saveProfile(payload)
  }

  const handleThemeChange = async (theme: 'light' | 'dark' | 'system') => {
    await updateSettings({ theme })
  }

  const handleRememberChange = async (enabled: boolean) => {
    await setRememberDevice(enabled)
    await updateSettings({ rememberDevice: enabled })
  }

  const handleExport = async () => {
    const blob = await exportBackup()
    downloadFile(blob, 'estate-dashboard-backup.zip')
  }

  const handleImport = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return
    setImportError('')
    try {
      await importBackup(file)
    } catch (error) {
      console.error('Failed to import backup', error)
      setImportError('Unable to import backup. Please ensure you selected a valid archive generated by this app.')
    } finally {
      event.target.value = ''
    }
  }

  const handleClear = async () => {
    setClearing(true)
    await clearAll()
    setForm(toFormState(null))
    setClearing(false)
  }

  return (
    <div className="space-y-6">
      <section className="card">
        <div className="card-header">
          <div>
            <h2 className="text-lg font-semibold">Estate profile</h2>
            <p className="text-sm text-slate-500">These dates drive statutory deadlines and task seeding.</p>
          </div>
        </div>
        <form className="card-body grid gap-4 md:grid-cols-2" onSubmit={handleSubmit}>
          <div>
            <label className="label" htmlFor="decedentFullName">
              Decedent full name
            </label>
            <input
              id="decedentFullName"
              name="decedentFullName"
              className="input"
              value={form.decedentFullName}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label className="label" htmlFor="dateOfDeath">
              Date of death
            </label>
            <input
              id="dateOfDeath"
              name="dateOfDeath"
              type="date"
              className="input"
              value={form.dateOfDeath}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label className="label" htmlFor="lettersGrantedDate">
              Letters granted date
            </label>
            <input
              id="lettersGrantedDate"
              name="lettersGrantedDate"
              type="date"
              className="input"
              value={form.lettersGrantedDate}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label className="label" htmlFor="firstAdvertisementDate">
              First advertisement date
            </label>
            <input
              id="firstAdvertisementDate"
              name="firstAdvertisementDate"
              type="date"
              className="input"
              value={form.firstAdvertisementDate}
              onChange={handleChange}
            />
          </div>
          <div>
            <label className="label" htmlFor="county">
              County
            </label>
            <input
              id="county"
              name="county"
              className="input"
              value={form.county}
              onChange={handleChange}
              placeholder="Chester"
            />
          </div>
          <div>
            <label className="label" htmlFor="state">
              State
            </label>
            <input id="state" name="state" className="input" value={form.state} onChange={handleChange} placeholder="PA" />
          </div>
          <div>
            <label className="label" htmlFor="fileNumber">
              File number
            </label>
            <input id="fileNumber" name="fileNumber" className="input" value={form.fileNumber} onChange={handleChange} />
          </div>
          <div>
            <label className="label" htmlFor="contactName">
              Executor contact name
            </label>
            <input id="contactName" name="contactName" className="input" value={form.contactName} onChange={handleChange} />
          </div>
          <div>
            <label className="label" htmlFor="contactEmail">
              Contact email
            </label>
            <input id="contactEmail" name="contactEmail" type="email" className="input" value={form.contactEmail} onChange={handleChange} />
          </div>
          <div>
            <label className="label" htmlFor="contactPhone">
              Contact phone
            </label>
            <input id="contactPhone" name="contactPhone" className="input" value={form.contactPhone} onChange={handleChange} />
          </div>
          <div className="md:col-span-2">
            <label className="label" htmlFor="contactAddress">
              Mailing address for notices
            </label>
            <textarea
              id="contactAddress"
              name="contactAddress"
              className="input"
              rows={3}
              value={form.contactAddress}
              onChange={handleChange}
            />
          </div>
          <div className="md:col-span-2 flex items-center gap-3">
            <button type="submit" className="btn btn-primary">
              Save profile
            </button>
            <p className="text-xs text-slate-500">Task deadlines update automatically after saving.</p>
          </div>
        </form>
      </section>

      <section className="card">
        <div className="card-header">
          <h2 className="text-lg font-semibold">Preferences</h2>
        </div>
        <div className="card-body space-y-4">
          <div>
            <p className="label mb-1">Theme</p>
            <div className="flex flex-wrap gap-3">
              {['light', 'dark', 'system'].map((theme) => (
                <label key={theme} className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300">
                  <input
                    type="radio"
                    name="theme"
                    value={theme}
                    checked={settings.theme === theme}
                    onChange={() => handleThemeChange(theme as 'light' | 'dark' | 'system')}
                  />
                  {theme === 'system' ? 'Match system' : theme.charAt(0).toUpperCase() + theme.slice(1)}
                </label>
              ))}
            </div>
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300">
              <input
                type="checkbox"
                className="h-4 w-4 rounded border-slate-300 text-brand-500 focus:ring-brand-500"
                checked={rememberDevice}
                onChange={(event) => void handleRememberChange(event.target.checked)}
              />
              Remember this device for quicker sign-in
            </label>
          </div>
        </div>
      </section>

      <section className="card">
        <div className="card-header flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold">Backup & restore</h2>
            <p className="text-sm text-slate-500">Data stays on this device. Export backups regularly.</p>
          </div>
          <div className="flex items-center gap-2">
            <button type="button" className="btn btn-secondary" onClick={handleExport}>
              Export backup
            </button>
            <label className="btn btn-secondary cursor-pointer">
              Import backup
              <input type="file" accept="application/zip" className="hidden" onChange={handleImport} />
            </label>
          </div>
        </div>
        {importError && <p className="px-6 pb-4 text-sm text-rose-500">{importError}</p>}
      </section>

      <section className="card border border-rose-200 dark:border-rose-500/40">
        <div className="card-header">
          <h2 className="text-lg font-semibold text-rose-600 dark:text-rose-300">Danger zone</h2>
        </div>
        <div className="card-body space-y-3">
          <p className="text-sm text-slate-500">Clearing the workspace removes all local data, including documents. This cannot be undone.</p>
          <button type="button" className="btn btn-secondary text-rose-600" onClick={() => void handleClear()} disabled={clearing}>
            {clearing ? 'Clearing…' : 'Clear all data'}
          </button>
        </div>
      </section>
    </div>
  )
}
